### ISSUE TITLE
Processing legacy "View Engine" libraries message

### ISSUE THREAD

**Issue by lamhuynhorient** [dmester/ngx-jdenticon#11]
Hi. My app is on angular 14 version. I get this message when running ng serve:
\ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-jdenticon [es2015/esm2015] (https://github.com/dmester/ngx-jdenticon)
Encourage the library authors to publish an Ivy distribution.
√ Browser application bundle generation complete.

**Comment by dmester** [comment]
Hello! The package is now upgraded to a newer Angular version using the Ivy engine. Upgrade `ngx-jdenticon` to version 2.0.0 and `jdenticon` to version 3.2.0 to remove the build warning:

```
npm install --save ngx-jdenticon@2.0.0 jdenticon@3.2.0
```
